-- PACKER INSTALLED
return require('packer').startup(function()
		use 'SirVer/ultisnips'
		use 'ThePrimeagen/harpoon'
		use 'godlygeek/tabular'                                    
		use 'hrsh7th/cmp-buffer'
		use 'hrsh7th/cmp-nvim-lsp'
		use 'hrsh7th/cmp-nvim-lua'
		use 'hrsh7th/cmp-path'
		use 'hrsh7th/nvim-cmp'
		use 'junegunn/goyo.vim'
		use 'kyazdani42/nvim-tree.lua'	
		use 'kyazdani42/nvim-web-devicons'
		use 'lervag/vimtex'                                        
		use 'mbbill/undotree'
		use 'morhetz/gruvbox'
		use 'neovim/nvim-lspconfig'                                
		use 'nvim-lua/plenary.nvim'
		use 'nvim-lua/popup.nvim'
		use 'nvim-lualine/lualine.nvim'
		use 'nvim-telescope/telescope.nvim'
		use 'nvim-treesitter/nvim-treesitter'
		use 'nvim-treesitter/playground'
		use 'quangnguyen30192/cmp-nvim-ultisnips'
		use 'sbdchd/neoformat'
		use 'tpope/vim-commentary'                                
		use 'tpope/vim-fugitive'                                   
		use 'tpope/vim-surround'                                 
		use 'vimwiki/vimwiki'
		use 'wbthomason/packer.nvim'
		use 'windwp/nvim-autopairs'
	end)

